


<div style="width:1000px;">
    <div style="padding: 15px; background: #efefef;">

        <div style="background: #ffffff; margin: 15px; border: 1px solid #dedede; padding: 15px; ">


            <h2 style="font-family: arial; margin-top: 0px;">Daily Cheques Deposits Reminder</h2>

            <div>
                <table width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
                    <tr>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;"></th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">CUSTOMER</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">CHEQUE NO#</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">BANK</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">BRANCH</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: right;">AMOUNT</th>
                    </tr>


                    <?php
                    $list = UsersDevices::model()->findAllByAttributes(array("users_id" => $users_id, "online" => 1));


                    $amountTotal = 0;
                    $num = 1;

                    foreach ($list as $value) {

                        $device_id = $value->device_id;
                        $device = Device::model()->findByPk($device_id);
                        
                        $dataList = Yii::app()->db->createCommand("SELECT id FROM payment WHERE pd_date = '" . date("Y-m-d") . "' AND device_id = '$device_id' AND online = 1 AND pay_type = 'BANK' ")->queryAll();
                        
                        foreach ($dataList as $valueRecords) {
                            
                            
                            
                            $payment = Payment::model()->findByPk($valueRecords['id']);
                            
                            ?>
                            <tr style="<?php echo $bg; ?>">
                                <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $num; ?></td>
                                <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $payment->customers->name; ?></td>
                                <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $payment->cheque_no; ?></td>
                                <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $payment->bank_name; ?></td>
                                <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $payment->branch_name; ?></td>
                                <td style="padding: 10px;border: 1px solid #dedede; text-align: right;"><?php echo number_format($payment->amount,2); ?></td>
                            </tr>
                            <?php
                            
                            $amountTotal += $payment->amount;                            
                            $num += 1;
                        }
                    }
                    ?>

                    <tr>
                        <td style="padding: 10px;border: 1px solid #dedede; text-align: left; background: #eeeeee"></td>
                        <td style="padding: 10px;border: 1px solid #dedede; text-align: left; background: #eeeeee" colspan="4">Total</td>
                        <td style="padding: 10px;border: 1px solid #dedede; text-align: right; background: #eeeeee"><?php echo number_format($amountTotal, 2); ?></td>

                    </tr>

                </table>
            </div>
            <p style="font-family: arial; font-size: 12px; color: #b6b6b6;">
                This Report Generated by Prologics iForce Email Notification Module @ <?php echo date("Y-m-d H:i:s"); ?>
            </p>




        </div>


    </div>
</div>