<?php 
$today = date("Y-m-d");
$effdate = date("Y-m-d",  strtotime("$today -1 day"));

?>
<div>
    <div style="padding: 15px; background: #efefef;">

        <div style="background: #ffffff; margin: 15px; border: 1px solid #dedede; padding: 15px; ">


            <h2 style="font-family: arial;">Field Sales Performance - <?php echo $effdate; ?></h2>

            <div>
                <table width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
                    <tr>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;"></th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">Location</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">First Bill</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">Last Bill</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">Calls</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">Working Gap</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">Total</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: right;">%</th>
                    </tr>


                    <?php
                    $list = UsersDevices::model()->findAllByAttributes(array("users_id" => $users_id, "online" => 1));
                    
                    
                    $num = 1;
                    
                    foreach ($list as $value) {

                        $device_id = $value->device_id;
                        $device = Device::model()->findByPk($device_id);
                        $data = Yii::app()->db->createCommand("SELECT SUM(invoice_total) as tot,count(id) as calls,MIN(eff_date) AS first_inv,MAX(eff_date) as last_inv,TIMEDIFF(MAX(eff_date),MIN(eff_date)) as avg_time FROM invoice WHERE device_id = '$device_id' AND DATE(eff_date) = '$effdate' ")->queryRow();

                        $d_target = round($device->target / 25, 2);
                        $baltotarget = $d_target - $data['tot'];

                        
                        ?>
                        <tr>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $num; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $device->name; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $data['first_inv']; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $data['last_inv']; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $data['calls']; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $data['avg_time']; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: right;"><?php echo number_format($data['tot'],2); ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: right;"><?php echo round($data['tot']/$d_target * 100,2); ?> %</td>
                        </tr>
                        <?php                       
                        
                        $num += 1;
                    }
                    ?>

                </table>
            </div>
            <p style="font-family: arial; font-size: 12px; color: #b6b6b6;">
                This Report Generated by Prologics iForce Email Notification Module @ <?php echo date("Y-m-d H:i:s"); ?>
            </p>




        </div>


    </div>
</div>