<div>
    <div style="padding: 10px; background: #efefef;">

        <div style="background: #ffffff; margin: 15px; border: 1px solid #dedede; padding: 10px; ">


            <h2 style="font-family: arial;">No Moving Items Notification</h2>
            <p>This report reflect, <b>Stock Available</b> but no <b>Sales</b> Triggered item list within this month. </p>
              

            <div style="overflow-x:auto;">
                <table  cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
                    <tr>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;"></th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">Code</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: left;">Item Name</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: right;">MRP</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: right;">COST</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: right;">Avl</th>
                        <th style="padding: 10px;border: 1px solid #dedede; text-align: right;">Valuation</th>
                    </tr>


                    <?php
                    $list = UsersDevices::model()->findAllByAttributes(array("users_id" => $users_id, "online" => 1));
                    $device_id = "";
                    foreach ($list as $value) {
                        $device_id .= $value->device_id.",";
                    }
                    $device_id = rtrim($device_id,",");
                    
                    $dataList = Yii::app()->db->createCommand("SELECT SUM(qty) as qtytot,SUM(qty * cost) as valv,items_id FROM `stock` WHERE device_id IN ($device_id) AND items_id NOT IN (SELECT items_id FROM invoice_items WHERE DATE(eff_date) >= '".date("y-m-1")."' AND device_id IN ($device_id) GROUP BY items_id) GROUP BY items_id HAVING qtytot > 0  ORDER BY valv DESC")->queryAll();

                    $num = 1;
                    $tot = 0;
                    foreach ($dataList as $value) {
                        
                        $item = Items::model()->findByPk($value['items_id']);
                        ?>
                        <tr style="<?php echo $bg; ?>">
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $num; ?></td>  
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $item->code; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: left;"><?php echo $item->item_name; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: right;"><?php echo $item->mrp; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: right;"><?php echo $item->cost; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: right;"><?php echo $value['qtytot']; ?></td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: right;"><?php echo number_format($value['valv'],2); ?></td>
                        </tr>
                        <?php
                        $num += 1;
                        $tot += $value['valv'];
                    }
                    ?>
                        
                        
                        <tr>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: right;" colspan="6">Total</td>
                            <td style="padding: 10px;border: 1px solid #dedede; text-align: right;"><?php echo number_format($tot,2); ?></td>
                                
                        </tr>   

                </table>
            </div>
            <p style="font-family: arial; font-size: 12px; color: #b6b6b6;">
                This Report Generated by Prologics iForce Email Notification Module @ <?php echo date("Y-m-d H:i:s"); ?>
            </p>




        </div>


    </div>
</div>